### ISSUE TITLE
Adding new line

### ISSUE THREAD

**Issue by sergeevabc** [zetamatta/csview#1]
Dear @zetamatta,
I’m looking for a tool to create table cells filled with data. CSView allows to insert (i) and append (a) cells, but it does so within a single line only. How do I add a new line?

```t
$ type data.csv
City, Country

$ csview data.csv
City   Country
Moscow Russia         <-- How to create this line?
```

**Comment by zetamatta** [comment]
Thank you for using csview! 

Now, I implemented them. Please try [the new version](https://github.com/zetamatta/csview/releases/tag/20200327).

* `o` - append a new line after the current line.
* `O` - insert a new line before the current line.
* `D` - delete the current line.

**Comment by sergeevabc** [comment]
@zetamatta, thanks you, it works as expected now.
However I am confused why a new piece of data is not saved when I quit.
Perhaps there should be three options: quit with saving, quit w/o saving, cancel.
